spring.application.name=ShipHub

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.from=uk.ship@mail.ru
spring.mail.protocol=smtps
spring.mail.username=uk.ship@mail.ru
spring.mail.password=pFhVStanxFlY9OWB0LIE
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=true

jwt.secret="secret"
mail.address=uk.ship@mail.ru
